"""Container integration tests.

Spins up the full stack (postgres + authentication) via docker-compose.test.yml,
using secrets generated by scripts/setup-env.sh into a temp file so no
credentials are committed to the repo and the script itself is exercised.

Set BASE_URL to skip compose startup and target an already-running instance.

Coverage is not collected here. src/gunicorn_logger.py is exercised by this
suite and is therefore excluded from the unit-test coverage report.
"""

import os
import pathlib
import subprocess
import tempfile

import pytest
import requests

BASE_URL = os.environ.get("BASE_URL", "").rstrip("/")
_REPO_ROOT = pathlib.Path(__file__).parents[2]
_COMPOSE_FILES = [
    "-f", str(_REPO_ROOT / "docker-compose.yml"),
    "-f", str(_REPO_ROOT / "docker-compose.test.yml"),
]


@pytest.fixture(scope="module")
def live_server():
    """Generate secrets, bring up the compose stack, yield the base URL,
    then tear down regardless of test outcome.

    Skipped when BASE_URL is set (caller manages the server).
    """
    if BASE_URL:
        yield BASE_URL
        return

    with tempfile.NamedTemporaryFile(suffix=".env", delete=False) as tmp:
        tmp_env = tmp.name

    try:
        subprocess.run(
            ["bash", str(_REPO_ROOT / "scripts" / "setup-env.sh"), "--force"],
            env={**os.environ, "ENV_FILE": tmp_env},
            cwd=str(_REPO_ROOT),
            check=True,
        )
        subprocess.run(
            ["docker", "compose", *_COMPOSE_FILES, "up", "-d", "--build", "--wait"],
            env={**os.environ, "TEST_ENV_FILE": tmp_env},
            cwd=str(_REPO_ROOT),
            check=True,
        )
        yield "http://localhost:8014"
    finally:
        subprocess.run(
            ["docker", "compose", *_COMPOSE_FILES, "down", "-v"],
            env={**os.environ, "TEST_ENV_FILE": tmp_env},
            cwd=str(_REPO_ROOT),
        )
        pathlib.Path(tmp_env).unlink(missing_ok=True)


def test_health(live_server):
    resp = requests.get(f"{live_server}/api/health", timeout=5)
    assert resp.status_code == 200
    assert resp.json() == {"status": "ok"}


def test_openapi_spec_is_served(live_server):
    """GET /api/openapi.json must return a valid JSON document with the
    expected top-level OpenAPI fields, proving the spec was loaded and Gunicorn
    is routing correctly.
    """
    resp = requests.get(f"{live_server}/api/openapi.json", timeout=5)
    assert resp.status_code == 200
    spec = resp.json()
    assert "openapi" in spec
    assert "info" in spec
    assert "paths" in spec


def test_unauthenticated_me_returns_401(live_server):
    """GET /api/me without a token must return 401, proving auth middleware
    is active and the request traversed the full application stack.
    """
    resp = requests.get(f"{live_server}/api/me", timeout=5)
    assert resp.status_code == 401
