name: authentication-ci

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  test:
    name: Test & Coverage
    uses: Neosofia/platform-workflows/.github/workflows/authentication-_test.yml@main
    with:
      upload_coverage: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  scan:
    name: Vulnerability Scan
    uses: Neosofia/platform-workflows/.github/workflows/authentication-_scan.yml@main
